language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: zlebnik
  password:
    secure: gG6N+HzBZcw7HmE4+J1MO7q/EyWH9ekym9lEC7cslrSywQ7pLwcjgZdcSDKjJUdfkoMM9SUv/e5wsAmNRTI7vfLvmckNOt9D3zGZVzegDbxXwfkd0GmZvpnLQDb5WQZfjJUgL0PKYLxORLL1UsE8F+nKnjmFOoZhr2kzlsAVI1hfcuBDcKle+dC0X3zHj+gPcQ9VeVizn5l0cisiVFDpH29F1MBuQsH6BI1A1s/rVlCcKGNJRugnQbLExb1vJG15Xa8FxGSjkeH5PtHbMrzDRrdBuJlQDZP/zg6hE4ZbDvK1tL4gD9Tt+Ykt8aN2ZPlvyPEHlfuuKcqGbMGK7wfB2ne8fweEA4joKWFGeTZ54Kaq09qCDHzCGMNx4U7OEjoWpdG/tdtjei6jprvPcg2pLyMap+vl/J7CFjkb4ui1Sj8AdLFEY7XrqS9TtMRQSJqrNmtfVEzePT5bA+UTSzmGqLgUw7rHoQHi3Gx0k2Kot3aU6Ov2Cs2sR7rD/F+0E4jzDl02vu9grXBYslmG1al5vIF9DN2sEKRM7AseW7KIxwJocnd11CYwqWTtzn63IMbxKJEVsC1riq24neYIHosr+lnnv+PXl2X7zuG+5Amc520hx6eNxw2f96f2L0xQy/Npz7GeGL3JSHp/UJyUHAvRQNYNr9Owi0JYTTFU0b3iuvk=
  on:
    tags: true
    repo: zlebnik/mongo_filter_evaluator
    python: 2.7
